### ISSUE TITLE
No main.tscn in a repo

### ISSUE THREAD

**Issue by chapayGhub** [BraindeadBZH/godot_card_engine#1]
**main.tscn** exist in a **.gitignore**

It's a reason why i can't 

_"Create a new scene which inherit from "res://addons/card_engine/demo/main.tscn" and set it as the main scene in the project settings"_

**Comment by BraindeadBZH** [comment]
OK didn't realized that it would also apply to sub-folders too, that's different from Mercurial.

**Comment by BraindeadBZH** [comment]
Fixed with a213ded32db70b146d07f84c8ef1416f7cb2ce0b
