### ISSUE TITLE
plugin_main.gd problem

### ISSUE THREAD

**Issue by sagagt505** [BraindeadBZH/godot_card_engine#10]
I follow the setup step5 but ut said it unable to load script from path res...../card_engine/plugin_main.gd

So I open the code and change 
preload("res://addons/card_engine/widgets/widget_card.gd"), to
load("res://addons/card_engine/widgets/widget_card.gd"),

It work fine only menu interfacebut gameplay is broken... anyway how to fix it thank you...

**Comment by BraindeadBZH** [comment]
The plugin has been completely reworked.
