### ISSUE TITLE
Does the reworked version still contains a Demo for New Game

### ISSUE THREAD

**Issue by TurtleTaco** [BraindeadBZH/godot_card_engine#12]
Thank you so much for making this engine, as a starter on Godot it really helped me a lot learning from example and some best practices. Thank you so much!

I noticed in the demo, there are three options, library and quit game work and can successfully switch scenes, but New Game does not trigger a scene switch. I am wondering if the card animation part still exist in the latest version of this engine?

Thank you in advance!

**Comment by BraindeadBZH** [comment]
As stated, the project is very much work-in-progress, not even alpha state, so yes some part are still missing.

However, yes a demo will be implemented. Even more, the new CardEngine will be distributed as a full Godot project template that will come will many examples on how to use it.

**Comment by TurtleTaco** [comment]
Thank you so much for the prompt response! I will look into your engine a bit more and see where I can go from there. Appreciated!
