### ISSUE TITLE
Looking forward!

### ISSUE THREAD

**Issue by Gamecrazy** [BraindeadBZH/godot_card_engine#13]
I've been waiting for this for a long time, looking forward to it!!!! Hope to finish the first version of Godot 3.2.2 as soon as possible!

**Comment by BraindeadBZH** [comment]
Thank you. I'm currently working on the animation part, which is quite complex as I want it to be very flexible while being easy to use.

**Comment by Gamecrazy** [comment]
I support you！

**Comment by dantegarden** [comment]
It's awesome!  Hoping that we can use it as soon as possible.
