### ISSUE TITLE
Starting errors

### ISSUE THREAD

**Issue by SilentFireYT** [BraindeadBZH/godot_card_engine#16]
After downloading the zip file unzipping it and importing it into the godot engine you get these error messages and im wondering if any of these are relevant errors
 No loader found for resource: res://addons/cardengine/card/card_preview.png.
 No loader found for resource: res://addons/cardengine/card/card_preview_bg.png.
 No loader found for resource: res://addons/cardengine/card/card_preview.png.
 scene/resources/resource_format_text.cpp:175 - Couldn't load external resource: res://addons/cardengine/card/card_preview.png
 No loader found for resource: res://addons/cardengine/card/card_preview_bg.png.
 scene/resources/resource_format_text.cpp:175 - Couldn't load external resource: res://addons/cardengine/card/card_preview_bg.png
 editor/editor_node.cpp:3160 - Addon 'godot-plugin-refresher' failed to load. No directory found. Removing from enabled plugins.

**Comment by BraindeadBZH** [comment]
Probably linked to this issue in Godot:  https://github.com/godotengine/godot/issues/23937
As for the "godot-plugin-refresher", you can ignore or remove the addon from the settings. I use it for development purpose but it is not necessary when using CardEngine.
