### ISSUE TITLE
Any chance for multiplayer?

### ISSUE THREAD

**Issue by BigDC** [BraindeadBZH/godot_card_engine#17]
Any chance for multiplayer?
That would be awesome!

**Comment by BraindeadBZH** [comment]
I don't have any experience regarding multiplayer so I don't plan to add this as a feature anytime soon. You can, however, Let me know if you see unavoidable road blocks that prevent someone to make a multiplayer game with CardEngine.

**Comment by BigDC** [comment]
Ok, I know MP is very hard1

2 more questions...
#1 Are you going to add a targeting arrow/system?
#2 How do you load card images (characters, creatures, weapons, spells, or whatever) Can the picture file name be added to the database and then be loaded to the card when it gets created?

**Comment by BraindeadBZH** [comment]
#1 I'm not planning to, my idea is that someone can use a custom drag and drop widget to do so.
#2 If you look at the demo, the way I do it is by using the categories to define what to display on the card.
