### ISSUE TITLE
export as HTML5 fails

### ISSUE THREAD

**Issue by wordpad25** [BraindeadBZH/godot_card_engine#18]
Export to HTML5 fails, even when using GLES2, resulting in black screen only.

**Comment by BraindeadBZH** [comment]
What does the web console says?

**Comment by wordpad25** [comment]
In Chrome with GLES3:

templateengine.js:13 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
load	 @ templateengine.js:13
tmp_js_export.js:8 Godot Engine v3.2.3.stable.official - https://godotengine.org
tmp_js_export.js:8 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
ASM_CONSTS	 @ tmp_js_export.js:8
tmp_js_export.js:8 OpenGL ES 3.0 Renderer: WebKit WebGL
tmp_js_export.js:8  
tmp_js_export.js:8 **WARNING**: MSAA must be <= GL_MAX_SAMPLES, falling-back to GL_MAX_SAMPLES = 4
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: drivers/gles3/rasterizer_storage_gles3.cpp:7217:_render_target_allocate() - MSAA must be <= GL_MAX_SAMPLES, falling-back to GL_MAX_SAMPLES = 4
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **SCRIPT ERROR**: Parse Error: The identifier "EditorPlugin" isn't a valid type (not a script or class), or couldn't be found on base "self".
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: res://addons/cardengine/core/card_engine_instance.gdc:17:GDScript::load_byte_code() - Parse Error: The identifier "EditorPlugin" isn't a valid type (not a script or class), or couldn't be found on base "self".
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Method failed. Returning: ERR_PARSE_ERROR
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:801:load_byte_code() - Method failed. Returning: ERR_PARSE_ERROR
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot load byte code from file 'res://addons/cardengine/core/card_engine_instance.gdc'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:2282:load() - Condition "err != OK" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://addons/cardengine/core/card_engine_instance.gdc. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Can't autoload: res://addons/cardengine/core/card_engine_instance.gd
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: main/main.cpp:1757:start() - Condition "res.is_null()" is true. Continuing.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **WARNING**: MSAA must be <= GL_MAX_SAMPLES, falling-back to GL_MAX_SAMPLES = 4
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: drivers/gles3/rasterizer_storage_gles3.cpp:7217:_render_target_allocate() - MSAA must be <= GL_MAX_SAMPLES, falling-back to GL_MAX_SAMPLES = 4
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **WARNING**: MSAA must be <= GL_MAX_SAMPLES, falling-back to GL_MAX_SAMPLES = 4
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: drivers/gles3/rasterizer_storage_gles3.cpp:7217:_render_target_allocate() - MSAA must be <= GL_MAX_SAMPLES, falling-back to GL_MAX_SAMPLES = 4
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **WARNING**: MSAA must be <= GL_MAX_SAMPLES, falling-back to GL_MAX_SAMPLES = 4
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: drivers/gles3/rasterizer_storage_gles3.cpp:7217:_render_target_allocate() - MSAA must be <= GL_MAX_SAMPLES, falling-back to GL_MAX_SAMPLES = 4
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:829:load_source_code() - Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot load source code from file 'res://_private/containers//home_display/home_display_private.gd'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:2286:load() - Condition "err != OK" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://_private/containers//home_display/home_display_private.gd. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:829:load_source_code() - Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot load source code from file 'res://_private/containers//home_display/home_display_private.gd'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:2286:load() - Condition "err != OK" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://_private/containers//home_display/home_display_private.gd. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **WARNING**: Couldn't load external resource: res://_private/containers//home_display/home_display_private.gd
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: scene/resources/resource_format_text.cpp:175:_parse_ext_resource() - Couldn't load external resource: res://_private/containers//home_display/home_display_private.gd
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:829:load_source_code() - Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot load source code from file 'res://_private/containers//card_list/card_list_private.gd'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:2286:load() - Condition "err != OK" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://_private/containers//card_list/card_list_private.gd. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:829:load_source_code() - Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot load source code from file 'res://_private/containers//card_list/card_list_private.gd'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:2286:load() - Condition "err != OK" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://_private/containers//card_list/card_list_private.gd. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **WARNING**: Couldn't load external resource: res://_private/containers//card_list/card_list_private.gd
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: scene/resources/resource_format_text.cpp:175:_parse_ext_resource() - Couldn't load external resource: res://_private/containers//card_list/card_list_private.gd
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:829:load_source_code() - Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot load source code from file 'res://_private/containers//hand/hand_private.gd'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:2286:load() - Condition "err != OK" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://_private/containers//hand/hand_private.gd. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:829:load_source_code() - Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot load source code from file 'res://_private/containers//hand/hand_private.gd'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:2286:load() - Condition "err != OK" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://_private/containers//hand/hand_private.gd. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **WARNING**: Couldn't load external resource: res://_private/containers//hand/hand_private.gd
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: scene/resources/resource_format_text.cpp:175:_parse_ext_resource() - Couldn't load external resource: res://_private/containers//hand/hand_private.gd
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:829:load_source_code() - Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot load source code from file 'res://_private/containers//token_grid/token_grid_private.gd'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:2286:load() - Condition "err != OK" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://_private/containers//token_grid/token_grid_private.gd. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:829:load_source_code() - Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot load source code from file 'res://_private/containers//token_grid/token_grid_private.gd'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:2286:load() - Condition "err != OK" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://_private/containers//token_grid/token_grid_private.gd. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **WARNING**: Couldn't load external resource: res://_private/containers//token_grid/token_grid_private.gd
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: scene/resources/resource_format_text.cpp:175:_parse_ext_resource() - Couldn't load external resource: res://_private/containers//token_grid/token_grid_private.gd
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:829:load_source_code() - Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot load source code from file 'res://_private/containers//visible_pile/visible_pile_private.gd'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:2286:load() - Condition "err != OK" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://_private/containers//visible_pile/visible_pile_private.gd. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:829:load_source_code() - Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot load source code from file 'res://_private/containers//visible_pile/visible_pile_private.gd'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:2286:load() - Condition "err != OK" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://_private/containers//visible_pile/visible_pile_private.gd. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **WARNING**: Couldn't load external resource: res://_private/containers//visible_pile/visible_pile_private.gd
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: scene/resources/resource_format_text.cpp:175:_parse_ext_resource() - Couldn't load external resource: res://_private/containers//visible_pile/visible_pile_private.gd
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot open file 'res://_private/containers//hidden_pile/hidden_pile_private.tscn'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: scene/resources/resource_format_text.cpp:1228:load_interactive() - Condition "err != OK" is true. Returned: Ref<ResourceInteractiveLoader>()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://_private/containers//hidden_pile/hidden_pile_private.tscn. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:829:load_source_code() - Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot load source code from file 'res://containers//hidden_pile/hidden_pile.gd'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:2286:load() - Condition "err != OK" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://containers//hidden_pile/hidden_pile.gd. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot open file 'res://_private/containers//hidden_pile/hidden_pile_private.tscn'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: scene/resources/resource_format_text.cpp:1228:load_interactive() - Condition "err != OK" is true. Returned: Ref<ResourceInteractiveLoader>()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://_private/containers//hidden_pile/hidden_pile_private.tscn. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **WARNING**: Couldn't load external resource: res://_private/containers//hidden_pile/hidden_pile_private.tscn
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: scene/resources/resource_format_text.cpp:175:_parse_ext_resource() - Couldn't load external resource: res://_private/containers//hidden_pile/hidden_pile_private.tscn
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:829:load_source_code() - Condition "err" is true. Returned: err
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Cannot load source code from file 'res://containers//hidden_pile/hidden_pile.gd'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: modules/gdscript/gdscript.cpp:2286:load() - Condition "err != OK" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **ERROR**: Failed loading resource: res://containers//hidden_pile/hidden_pile.gd. Make sure resources have been imported by opening the project in the editor at least once.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: core/io/resource_loader.cpp:279:_load() - Condition "found" is true. Returned: RES()
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **WARNING**: Couldn't load external resource: res://containers//hidden_pile/hidden_pile.gd
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: scene/resources/resource_format_text.cpp:175:_parse_ext_resource() - Couldn't load external resource: res://containers//hidden_pile/hidden_pile.gd
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **SCRIPT ERROR**: Invalid call. Nonexistent function 'clean' in base 'Nil'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: res://main.gdc:15:_ready() - Invalid call. Nonexistent function 'clean' in base 'Nil'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **SCRIPT ERROR**: Invalid call. Nonexistent function 'general' in base 'Nil'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: res://main.gdc:23:_unhandled_input() - Invalid call. Nonexistent function 'general' in base 'Nil'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **SCRIPT ERROR**: Invalid call. Nonexistent function 'general' in base 'Nil'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: res://main.gdc:23:_unhandled_input() - Invalid call. Nonexistent function 'general' in base 'Nil'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **SCRIPT ERROR**: Invalid call. Nonexistent function 'general' in base 'Nil'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: res://main.gdc:23:_unhandled_input() - Invalid call. Nonexistent function 'general' in base 'Nil'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **SCRIPT ERROR**: Invalid call. Nonexistent function 'general' in base 'Nil'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: res://main.gdc:23:_unhandled_input() - Invalid call. Nonexistent function 'general' in base 'Nil'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.html:1 [.WebGL-0000636C00142080]GL ERROR :GL_INVALID_OPERATION : GetShaderiv: <- error from previous GL command
tmp_js_export.html:1 [.WebGL-0000636C00142080]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: <- error from previous GL command
tmp_js_export.js:8 **SCRIPT ERROR**: Invalid call. Nonexistent function 'general' in base 'Nil'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: res://main.gdc:23:_unhandled_input() - Invalid call. Nonexistent function 'general' in base 'Nil'.
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **WARNING**: MSAA must be <= GL_MAX_SAMPLES, falling-back to GL_MAX_SAMPLES = 4
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8    At: drivers/gles3/rasterizer_storage_gles3.cpp:7217:_render_target_allocate() - MSAA must be <= GL_MAX_SAMPLES, falling-back to GL_MAX_SAMPLES = 4
put_char	 @ tmp_js_export.js:8
tmp_js_export.js:8 **WARNING**: MSAA must be <= GL_MAX_SAMPLES, falling-back to GL_MAX_SAMPLES = 4
put_char	 @ tmp_js_export.js:8
write	 @ tmp_js_export.js:8
write	 @ tmp_js_export.js:8
doWritev	 @ tmp_js_export.js:8
_fd_write	 @ tmp_js_export.js:8
__stdio_write	 @ 04e1da72:0x6abdc1
__vfprintf_internal	 @ 04e1da72:0x17b692
vfprintf	 @ 04e1da72:0x11a67f
StdLogger::logv(char const*, void*, bool)	 @ 04e1da72:0x7db4e6
Logger::logf_error(char const*, ...)	 @ 04e1da72:0x14bc8c
Logger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType)	 @ 04e1da72:0xb5901c
CompositeLogger::log_error(char const*, char const*, int, char const*, char const*, Logger::ErrorType)	 @ 04e1da72:0xc3cf43
_err_print_error(char const*, char const*, int, char const*, char const*, ErrorHandlerType)	 @ 04e1da72:0x2ccb6
_err_print_error(char const*, char const*, int, String const&, ErrorHandlerType)	 @ 04e1da72:0x35387
RasterizerStorageGLES3::_render_target_allocate(RasterizerStorageGLES3::RenderTarget*)	 @ 04e1da72:0x1a1f50
RasterizerStorageGLES3::render_target_set_size(RID, int, int)	 @ 04e1da72:0x88a4d7
VisualServerViewport::viewport_set_size(RID, int, int)	 @ 04e1da72:0x71da5d
VisualServerRaster::viewport_set_size(RID, int, int)	 @ 04e1da72:0x725f66
Viewport::set_size(Vector2 const&)	 @ 04e1da72:0xe3ee8
SceneTree::_update_root_rect()	 @ 04e1da72:0x13dda5
SceneTree::idle(float)	 @ 04e1da72:0x84740e
Main::iteration()	 @ 04e1da72:0xb581c1
OS_JavaScript::main_loop_iterate()	 @ 04e1da72:0x95f081
main_loop_callback()	 @ 04e1da72:0x21ce41
dynCall_v	 @ 04e1da72:0x6514e8
Module.dynCall_v	 @ tmp_js_export.js:8

**Comment by BraindeadBZH** [comment]
`The identifier "EditorPlugin" isn't a valid type (not a script or class), or couldn't be found on base "self".`
This I can do something about. I have a conceptual error that make exported projects dependent on the EditorPlugin class.

`ERROR: Cannot load source code from file 'res://_private/containers//home_display/home_display_private.gd'.`
If not a consequence of the first error, I don't understand why it is not working.

**Comment by BraindeadBZH** [comment]
The same issue is also present when exporting for Windows, and I suppose for other platform also. Found a workaround for EditorPlugin. Not sure what's going on with the other errors.

**Comment by wordpad25** [comment]
What's the EditorPlugin workaround?

**Comment by BraindeadBZH** [comment]
I still have to fix one last issue and I will push all the fixes to the repo.

**Comment by BraindeadBZH** [comment]
Fixed as of v0.2
