### ISSUE TITLE
Error when trying to run demo

### ISSUE THREAD

**Issue by BigDC** [BraindeadBZH/godot_card_engine#2]
I have followed your demo tutorial, and it gives me an error when I try to start the project, here is the error....     Parser Error: Identifier not found: DemoGame

**Comment by BraindeadBZH** [comment]
Yes, you are right, I forgot a step in my documentation. There is a third singleton to add called DemoGame. Fixed the documentation abe46987ac339027b5e2a4aef1b0982355cb6c2c
