### ISSUE TITLE
Bug when trying to enable the add-on

### ISSUE THREAD

**Issue by LienRag** [BraindeadBZH/godot_card_engine#20]
When trying to enable the plugin in the Project Settings/extensions panel I got "Impossible de charger le script de l’extension depuis le chemin : « res://addons/cardengine/card_engine.gd ». Cela peut être dû à une erreur de programmation dans ce script.
L'extension « res://addons/cardengine/plugin.cfg » a été désactivée pour prévenir de nouvelles erreures." when trying to enable it in the Project Settings/extensions panel.

This in Godot 3.3.2, Godot 3.4.0 and Godot 3.5.0.

I did put the unzipped add-on directory inside the folder of my project, and I also tried to put the full unzipped directory in the addon directory.
Both were recognized by the "extensions" panel, but both gave the same error when trying to activate them.

**Comment by BraindeadBZH** [comment]
Sorry, you cannot just drop the CardEngine plugin in the project like that, this repo is supposed to be used as a template.
If you think you have all the files in place in your project directory, you might be missing the necessary AutoLoads that need to be present before activating the plugin.
![image](https://user-images.githubusercontent.com/3399852/187738837-dc3d1cbc-f941-4988-8d62-0e39f8c408ba.png)

You also need the project.cardengine file at the root of the project which contains folder paths that should exists.

PS: I did test this repo against Godot 3.5.0 and its working fine.
