### ISSUE TITLE
Does not support Godot 4.0 alpha 15

### ISSUE THREAD

**Issue by JoshDangIt** [BraindeadBZH/godot_card_engine#21]
As Godot is moving to 4.0 in the near future they have updated the api and at this time the card engine needs to go through a refactor to update to the latest version. Are there any plans to do this?

**Comment by BraindeadBZH** [comment]
I've started working on moving CardEngine to Godot 4, but took a different approach using modules.
The first module is available: https://github.com/BraindeadBZH/datalogue (which is similar to the database part of CardEngine).

**Comment by fnaith** [comment]
Just for curiosity, is godot4 branch ready for releasing on asset library ?
