### ISSUE TITLE
Scaling does not work at different resolutions

### ISSUE THREAD

**Issue by JoshDangIt** [BraindeadBZH/godot_card_engine#22]
When testing on higher resolution devices this library doesn't scale.

**Comment by BraindeadBZH** [comment]
Where is the issue, in editor or in game?
Can you provide screenshots?

**Comment by JoshDangIt** [comment]
https://cdn.discordapp.com/attachments/1014598799571828737/1015289334028574831/Screenshot_20220902-095655_Godot_Editor.jpg
https://cdn.discordapp.com/attachments/1014598799571828737/1015289334779359383/Screenshot_20220902-095704_Godot_Editor.jpg

In game

**Comment by BraindeadBZH** [comment]
This is the expected behavior, it respects the Godot's "Stretch" project settings.
