### ISSUE TITLE
How "yield" should be used

### ISSUE THREAD

**Issue by yulongyu** [BraindeadBZH/godot_card_engine#25]
I think you did a great job, I'm learning your plug-in code，but I don't understand what yield means.
func delete_effect() -> void:
	if yield():
		_manager.delete_effect(_fx_list.get_item_metadata(_selected_fx))

and how to use in godot4？？I know yield and await basic usage,But I don't understand the method without parameters

**Comment by BraindeadBZH** [comment]
Hello,
Thank you for the compliment.
This is a trick I used to be able to control the execution of a function using a dialog box.
It is used in combination with the generic_confirm_dialog.
Basically, yield will return the result of
```gdscript
func _on_GenericConfirmDialog_popup_hide() -> void:
	_ctx.resume(_confirmed)
```
Not sure how this can be translated in Godot 4.

**Comment by yulongyu** [comment]
> Hello, Thank you for the compliment. This is a trick I used to be able to control the execution of a function using a dialog box. It is used in combination with the generic_confirm_dialog. Basically, yield will return the result of
> 
> ```gdscript
> func _on_GenericConfirmDialog_popup_hide() -> void:
> 	_ctx.resume(_confirmed)
> ```
> 
> Not sure how this can be translated in Godot 4.

Thanks for the reply, I'm studying to learn your code
