### ISSUE TITLE
Struggling To Use CardEngine?

### ISSUE THREAD

**Issue by BigDC** [BraindeadBZH/godot_card_engine#4]
Hello,
I am really struggling trying to understand how to use your CardEngine.  I have read, reread, and reread all the documentation for the demo and the engine its self. Everything is just way to vague and void of the needed information. It seams like all the documentation is just made as a reminder to you what you did and how you use it and not geared to any other users at all.

The Demo's and the CardEngine's documentation on the website and in the code its self, it not very well done, and it leaves way too much guessing on the user's part on what each thing does and how to use it.. If the Demo would be better documented and it's code better documented showing how each thing relates to the CardEngine its self that might help.

I  also do not understand if the CardEngine adds functions for me to call and/or set, die to any good documentation.

Is there any way you can redo the documentation so it is more clear, more defined,  to us users?
Also, can you make a YouTube video showing EXACTLY how to use the CardEngine and each and everyone of its features?

Do you have an email address or discord channel to where I can communicate more efficiently with you?

Thank You!!!

**Comment by BraindeadBZH** [comment]
Hi,
Maybe I should have stated this more clearly, CardEngine is not finished and not really ready to be used by users. The Framework is not finished, the documentation is not finished. This project is something I have started on the side and unfortunately I don't have a lot of time to dedicated to.

I hope to be able to get back to it soon, and of course getting the documentation in better shape is in the pipeline.

**Comment by johnmanardiii** [comment]
Where is the project at currently? I think many of the aspects of this engine are extremely useful and would be useful if updated.

**Comment by BraindeadBZH** [comment]
The project is stalled at the moment, due to lack of time. I was expecting the project to gain so much attention. Still, I keep it in a corner of my brain, and I think about how I could make it more usable.

**Comment by BraindeadBZH** [comment]
The plugin has been completely reworked.
