### ISSUE TITLE
So it is not possible to use the CardEngine?

### ISSUE THREAD

**Issue by BigDC** [BraindeadBZH/godot_card_engine#6]
So am I to understand that it is not possible to use the CardEngine to create card games? As this would save me a lot of time and coding.

Also, may I suggest 2 separate json files. 1 for all the cards and 1 for the decks. A card collection could grow very, very, very big. Seperating the 2 would make it a little faster.

**Comment by BraindeadBZH** [comment]
The plugin has been completely reworked.
