### ISSUE TITLE
Unable to activate the plugin

### ISSUE THREAD

**Issue by elieobeid7** [BraindeadBZH/godot_card_engine#8]
I'm trying to follow the tutorial here

https://www.braindead.bzh/page/cardengine-demo

When I try to activate it, I keep getting this error

![Screenshot from 2019-04-14 02-47-16](https://user-images.githubusercontent.com/660142/56086434-e5b10b00-5e5f-11e9-84fc-2953043699e1.png)

**Comment by Permagate** [comment]
For anyone else who was struggling with this error, I managed to get it working by updating this line: https://github.com/BraindeadBZH/godot_card_engine/blob/master/addons/card_engine/plugin_main.gd#L9

Change `preload("res://addons/card_engine/widgets/widget_card.gd")` to `load("res://addons/card_engine/widgets/widget_card.gd")`

```
diff --git a/addons/card_engine/plugin_main.gd b/addons/card_engine/plugin_main.gd
index 59c5f10..ed0593a 100644
--- a/addons/card_engine/plugin_main.gd
+++ b/addons/card_engine/plugin_main.gd
@@ -6,7 +6,7 @@ func _enter_tree():
        print("CardEngine enabled")
        add_custom_type(
                "CardWidget", "Node2D",
-               preload("res://addons/card_engine/widgets/widget_card.gd"),
+               load("res://addons/card_engine/widgets/widget_card.gd"),
                preload("res://addons/card_engine/icons/card-node.png"))

        add_custom_type(
```

**Comment by elieobeid7** [comment]
Thank you.
