### ISSUE TITLE
how to play?

### ISSUE THREAD

**Issue by fastfading** [BraindeadBZH/godot_card_engine#9]
how to play the game?
I successfully compile the game in godot 3.2 dev
but found the game totally unplayable.
only can do pickup cards and drop cards,   nothing else.

could u give a feature list or road map ?
show what is done an what is in plan.
Anyway , Thank you for sharing this code.

**Comment by BraindeadBZH** [comment]
It is not suppose to be a game but a tool for Godot developers to create card games so it is normal there is not much to see. Unfortunately I don't have much time to work on it at the moment.
